<?php

/**
 * @file
 * Install, update and uninstall functions for Wildcat sites.
 */

/**
 * Implements hook_install().
 *
 * @todo Move most of this to submodules.
 */
function wildcat_os_install() {
  /** @var \Drupal\wildcat_os\WildcatOsConfigUuidMatcherInterface $matcher */
  $matcher = \Drupal::service('wildcat_os.config_uuid_matcher');

  // Set the site UUID, if there is a synced UUID.
  $matcher->matchUuids('system.site');
}
